# !!!!!
#
# NOTE: All relative filepaths are considered to be relative to this file
#
# !!!!!

mode = "dev"

# API related configurations
[dev.api]
allow_origins = ["http://localhost:3000", "http://localhost:4173"]
gh_repo_name = "gh-api-trial"
gh_repo_owner = "guacs"


[test.api]
gh_repo_name = "gh-api-trial"
gh_repo_owner = "guacs"

[prod.api]
gh_repo_name = "gh-api-trial"
gh_repo_owner = "guacs"


# Questions related configurations
[dev.questions]
whoosh_index_dir = "../../sample/dev/whoosh_index"
whoosh_questions_index_name = "questions"
questions_fp = "../../sample/dev/questions.json"
questions_index_fp = "../../sample/dev/.qindex.json"

[test.questions]
whoosh_index_dir = "../../sample/dev/whoosh_index"
whoosh_questions_index_name = "questions"
questions_fp = "../../sample/dev/questions.json"
questions_index_fp = "../../sample/dev/.qindex.json"

[prod.questions]
whoosh_index_dir = ""
whoosh_questions_index_name = "questions"
questions_fp = ""
questions_index_fp = ""

# Logging related configurations
[dev.logs]
format = "<magenta>{time:YYYY-MM-DD HH:mm:ss}</magenta> | <level>{level}</level> | <cyan>{extra[request_id]}</cyan> | {message}"
log_level = "trace"
serialize = false
sink = "../../logs/dev.log"

[test.logs]
format = "<green>{time:YYYY-MM-DD HH:mm:ss}</green> | <level>{level}</level> | <cyan>{extra[request_id]}</cyan> | {message}"
log_level = "debug"
serialize = false
sink = "../../logs/test.log"

[prod.logs]
format = ""
log_level = "info"
serialize = false
sink = "../../logs/prod.log"

# Database related configurations
[dev.db]
db_name = "past_years"
host = "localhost"

[test.db]
db_name = "test_past_years"
host = "localhost"

[prod.db]
db_name = "past_years"
host = ""
